services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  CI_REGISTRY_USER: arthurpaiva
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE_BACKEND: docker.io/arthurpaiva/workshop-ci-backend
  CI_REGISTRY_IMAGE_FRONTEND: docker.io/arthurpaiva/workshop-ci-frontend
  #CI_REGISTRY_PASSWORD is set in gitlab project settings
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-backend:
  image: docker:dind
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE_BACKEND:$CI_COMMIT_REF_SLUG" backend

build-frontend:
  image: docker:dind
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_REF_SLUG" frontend
    - docker-compose build

test-backend:
  image: docker:dind
  stage: test
  script:
    - docker-compose run --entrypoint "npm run unittest" backend

test-frontend:
  image: docker:dind
  stage: test
  script:
    - docker-compose run --entrypoint "npm run test" frontend

deploy-backend:
  image: docker:dind
  stage: deploy
  script:
    - docker image tag "$CI_REGISTRY_IMAGE_BACKEND:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE_BACKEND:ci-latest"
    - docker push "$CI_REGISTRY_IMAGE_BACKEND:ci-latest"
  only:
    - main

deploy-frontend:
  image: docker:dind
  stage: deploy
  script:
    - docker image tag "$CI_REGISTRY_IMAGE_FRONTEND:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE_FRONTEND:ci-latest"
    - docker push "$CI_REGISTRY_IMAGE_FRONTEND:ci-latest"
  only:
    - main
